v = input('Digite algo')
print('{} é alfanumerico? {}'.format(v, v.isalnum()))
print('{} é alfabetico?? {}'.format(v, v.isalpha()))
print(v.isascii())
print(v.isdigit())
print(v.islower())
print(v.isdecimal())
print(v.isidentifier())
print(v.isprintable())
print(v.isspace())
print(v.istitle())
print(v.isupper())